---
- name: Create config dir
  file: path="{{ ansible_env.HOME }}/.config" state=directory

- name: link vim config dir
  file: src="{{ ansible_env.HOME }}/.vim" dest="{{ ansible_env.HOME }}/.config/nvim" state=link

- name: link vimrc
  file: src="{{ ansible_env.HOME }}/.vimrc" dest="{{ ansible_env.HOME }}/.config/nvim/init.vim" state=link
