---
- name: Check nvim
  command: which nvim
  register: nvim_path

- file: path="{{ ansible_env.HOME }}/.local/share/nvim/site/autoload" state=directory
  when: nvim_path.stdout != ""

- name: Install vim-plug for nvim
  uri:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
    follow_redirects: safe
  when: nvim_path.stdout != ""

- file: path="{{ ansible_env.HOME }}/.vim/autoload" state=directory
  when: nvim_path.stdout == ""

- name: Install vim-plug for vim
  uri:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
    follow_redirects: safe
  when: nvim_path.stdout == ""
