---
- name: Install python3 (linux)
  apt: pkg=python3 state=latest
  become: yes
  when: ansible_os_family == "Debian"

# - name: Set symlink to python3 (linux)
#   file: src="/usr/bin/python3" dest="/usr/bin/python" state=link
#   when: ansible_os_family == "Debian"

- name: Install python3 (mac)
  homebrew: name=python3 state=latest
  when: ansible_os_family == "Darwin"
  become: false

- name: Install pip3 (linux)
  apt: pkg=python3-pip state=latest
  become: yes
  when: ansible_os_family == "Debian"

- name: Upgrade pip
  shell: pip3 install -U pip
  when: ansible_os_family == "Darwin"

- name: Install pipx (linux)
  apt: pkg=pipx state=latest
  become: yes
  when: ansible_os_family == "Debian"
