---
- file: path="{{ ansible_env.HOME }}/dev/tools" state=directory

- name: Download kotlin-language-sever
  git: repo=https://github.com/fwcd/kotlin-language-server.git dest="{{ ansible_env.HOME }}/dev/tools/kotlin-language-server" accept_hostkey=yes

- name: Build kotlin language server
  shell:
    cmd: ./gradlew :server:installDist
    chdir: "{{ ansible_env.HOME }}/dev/tools/kotlin-language-server"

- name: Create plugins directory
  file: path="{{ ansible_env.HOME }}/.vim/custom/plugins" state=directory

- name: Add kotlin plugins
  template: src="plugins/kotlin_plugins.vim" dest="{{ ansible_env.HOME }}/.vim/custom/plugins/kotlin_plugins.vim" mode=644

- name: Include plugins definition
  lineinfile: dest="{{ ansible_env.HOME }}/.vim/custom/plugins.vim" line="source {{ ansible_env.HOME }}/.vim/custom/plugins/kotlin_plugins.vim"

- name: Add kotlin autocmds
  template: src="autocmds/kotlin_autocmds.vim" dest="{{ ansible_env.HOME }}/.vim/custom/autocmds/kotlin_autocmds.vim" mode=644

- name: Include kotlin autocmds
  lineinfile: dest="{{ ansible_env.HOME }}/.vim/custom/autocmds.vim" line="source {{ ansible_env.HOME }}/.vim/custom/autocmds/kotlin_autocmds.vim"

- name: Check that the coc-settings exists
  stat:
    path: "{{ ansible_env.HOME }}/.vim/coc-settings.json"
  register: coc_settings_stat_result

- name: Read coc-config
  include_vars:
    file: "{{ ansible_env.HOME }}/.vim/coc-settings.json"
    name: coc_settings
  when: coc_settings_stat_result.stat.exists

- name: Render kotlin language server settings
  template:
    src: coc-settings.json.j2
    dest: "{{ ansible_env.TMPDIR }}/coc-settings.json"
    mode: '0644'

- name: Read kotlin language server settings
  include_vars:
    file: "{{ ansible_env.TMPDIR }}/coc-settings.json"
    name: kotlin_coc_settings

- name: Add kotlin language server settings
  copy:
    dest: "{{ ansible_env.HOME }}/.vim/coc-settings.json"
    content: "{{ coc_settings | default({}) | combine(kotlin_coc_settings, recursive=True) }}"

- name: Render kotlin init script from template
  template: src="init.lua" dest="{{ ansible_env.TMPDIR }}/kotlin_syntax_plugin_init.lua"

- name: Append syntax plugin init script to init lua
  blockinfile:
    path: "{{ ansible_env.HOME }}/.vim/lua/custom/init.lua"
    create: true
    marker: "-- {mark} Kotlin syntax plugin init"
    insertafter: EOF
    content: "{{ lookup('file', ansible_env.TMPDIR + '/kotlin_syntax_plugin_init.lua') }}"
