---
- name: Create plugins directory
  file: path="{{ ansible_env.HOME }}/.vim/custom/plugins" state=directory

- name: Add cpp plugins
  template: src="plugins/cpp_plugins.vim" dest="{{ ansible_env.HOME }}/.vim/custom/plugins/cpp_plugins.vim" mode=644

- name: Include plugins definition
  lineinfile: dest="{{ ansible_env.HOME }}/.vim/custom/plugins.vim" line="source {{ ansible_env.HOME }}/.vim/custom/plugins/cpp_plugins.vim"


