---
- name: Install vim (linux)
  apt: pkg=vim state=latest
  become: yes
  when: ansible_os_family == "Debian"

- name: Install vim (mac)
  homebrew: name=vim state=latest
  when: ansible_os_family == "Darwin"
  become: false
