---
- name: python3 pynvim (mac)
  # pip: name=pynvim virtualenv="{{ ansible_env.HOME }}/python-dev-env"
  pip:
    name: pynvim
    state: latest
    break_system_packages: true
    extra_args: --user
  when: ansible_os_family == "Darwin"

- name: Install neovim (mac)
  homebrew: name=neovim state=latest
  when: ansible_os_family == "Darwin"
  become: false

- name: Install software-properties-common (Ubuntu)
  apt: pkg=software-properties-common state=latest
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Add neovim apt repo (Ubuntu)
  shell: add-apt-repository ppa:neovim-ppa/unstable && apt-get update
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Install neovim (linux)
  apt: pkg=neovim state=latest
  become: yes
  when: ansible_os_family == "Debian"

- name: Install python3 neovim (linux)
  apt: name=python3-neovim state=latest
  become: true
  when: ansible_os_family == "Debian"
